export const IS_LOAD = "IS_LOAD";

export const POPULAR_LOADING = "POPULAR_LOADING";
export const GET_POPULAR = "GET_POPULAR";

export const GET_OVERVIEW_MOVIE = "GET_OVERVIEW_MOVIE";
export const OVERVIEW_LOADING = "OVERVIEW_LOADING";

export const GET_SIMILIAR_MOVIE = "GET_SIMILIAR_MOVIE";

export const GET_VIDEOS = "GET_VIDEOS";
export const VIDEO_LOADING = "VIDEO_LOADING";

export const GET_RECOMENDATIONS = "GET_RECOMENDATIONS";

export const GET_NOWPLAYING = "GET_NOWPLAYING";
export const NOWPLAYING_LOAD = "NOWPLAYING_LOAD";

export const GET_TOPRATED = "GET_TOPRATED";
export const TOPRATED_LOAD = "TOPRATED_LOAD";

export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const SEARCH_LOAD = "SEARCH_LOAD";

export const GET_GENRE = "GET_GENRE";
export const GENRE_LOAD = "GENRE_LOAD";

export const GET_LIST_GENRE = "GET_LIST_GENRE";
export const GET_LIST_GENRE_LOAD = "GET_LIST_GENRE_LOAD";
export const SAVE_GENRE = "SAVE_GENRE";
