export const POPULAR_LOADING = 'POPULAR_LOADING';
export const GET_POPULAR = 'GET_POPULAR';


export const GET_OVERVIEW_MOVIE = 'GET_OVERVIEW_MOVIE';
export const OVERVIEW_LOADING = 'OVERVIEW_LOADING';

export const GET_SIMILIAR_MOVIE = 'GET_SIMILIAR_MOVIE';
